### PR TITLE
CLI cleanups

### PR DESCRIPTION
**Pull request by heimweh**
This is an attempt to clean up the CLI a bit, there are some breaking changes involved related to flags and flag parsing.
More follow-up PRs to come but this lays the foundation 🙂

### CODE REVIEW

**Review by oliviermichaelis — APPROVED** [review]
Incredible work @heimweh :tada:
The code is much cleaner than before!

There were some flags in the README that needed to be updated to the POSIX style. I added 9c58ee6ebad175fc0ea0b53c9168dca5248a326e to clean that up as well as copy the help output into the README.


I've also added ae918b1b29454c99870876446f0776717c1c9a50 to extend the usage string for the `upload` command to make clear that the module argument is required: `boring-registry upload [flags] MODULE`.
We could also think about adding some verification in the future to make sure that users better understand how that would have to be used.

**Comment by oliviermichaelis** [comment]
I also just rebased on the latest `main`  :)

**Comment by pturbing** [comment]
Readme still need some serious revamping with all the changed flags.

should we introduce some short flags for commonly used ones? eazy peazy with cobra now

**Comment by oliviermichaelis** [comment]
> Should we introduce some short flags for commonly used ones?
I think the cli is not actually used in a terminal by humans that often, but mostly in scripts/CI. While having short flags don't hurt, I also see some value by being more explicit and therefore more readable by people unfamiliar with the cli flags

> Readme still need some serious revamping with all the changed flags.
Could you send a line reference to an example of what you mean? :)

**Comment by pturbing** [comment]
wrt Readme; nevermind. looked at the `main` branch

**Review by pturbing — APPROVED** [review]
ah, here is the approve button :D

**Pull request merged**
