### PR TITLE
to suppress usage output on upload errors 

### LINKED ISSUE #98: if `--ignore-existing=false` is set, existing modules in storage will clutter CI
Hi, I set the flag `--ignore-existing=false` and catch the error in CI myself.
Still I get the usage information displayed every time and thus clutter my CI output very much.

### PR DESCRIPTION
**Pull request by daniel-ciaglia**
Fixes #98 
Don't display usage on errors during upload. The error message is enough.

### CODE REVIEW

**Review by oliviermichaelis — APPROVED** [review]
Thanks for your contribution! 

LGTM :+1:

**Comment by oliviermichaelis** [comment]
Let me know if you need a new release :)

**Comment by daniel-ciaglia** [comment]
that would be awesome 😉

Thanks a bunch!

**Comment by oliviermichaelis** [comment]
Release [`v0.10.0`](https://github.com/TierMobility/boring-registry/releases/tag/v0.10.0) is there!

**Pull request merged**
